Use readfile() for serving protected uploads
dxw/dxw-members-only pull request #26
Opened 2024-05-22 14:02 UTC by leedxw

I suspect that one performance problem we have stems from loading binary files into memory, and then using `echo()` to send them to the client.

This switches off output buffering and uses `readfile()`.

- [ ] Version number has been bumped

2024-05-30 13:56 UTC, snim2 requested changes
So, I've tested this locally, and it still serves assets, so I think the change is fine. However, we need to update the Changelog before merging this.

2024-05-30 14:19 UTC, leedxw commented
You need to update the changelog, version string, git tagged version.

2024-06-17 11:06 UTC, RobjS commented
Do we have a recommended local config for testing this plugin on files in `uploads/`? By default, requests for files in that directory aren't routed via WordPress auth, so this plugin code doesn't run.

2024-06-17 11:23 UTC, leedxw commented
Is this for saluki testing?

`ENABLE_INTRANET_SETTINGS=true`

will force uploads to be delivered via `index.php`

2024-06-17 13:53 UTC, RobjS commented
No, this is for local testing using our `thedxw/wpc-wordpress` image

2024-06-28 10:10 UTC, snim2 commented
We've merged other things since this was raised so the version number needs to be checked

2024-06-28 13:34 UTC, RobjS reviewed
I've tested this locally with Saluki and it's working, just needs version number updating.

2024-06-28 13:44 UTC, snim2 commented on readme.txt
> +
@RobjS there are two README files in this plugin and this one is not displayed by default in GitHub. I'm inclined to delete it. wdyt?

2024-06-28 14:00 UTC, RobjS commented on readme.txt
> +
Yes, I think this is an artifact of when we published the plugin on the WordPress directory, but that's not the case in anymore, so happy to delete.

2024-06-28 14:15 UTC, snim2 approved these changes

2024-06-28 14:20 UTC, leedxw commented on readme.txt
> +
If it's a WordPress plugin it should be using the Wordpress plugin conventions regardless of if it's published imo.

2024-06-28 14:55 UTC, merged